<?php
/**
 * DefaultApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Earthpoints API
 *
 * Earthpoints API description
 *
 * The version of the OpenAPI document: 0.1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DefaultApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for appControllerCreate
     *
     * .
     *
     */
    public function testAppControllerCreate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for appControllerDashboard
     *
     * .
     *
     */
    public function testAppControllerDashboard()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for appControllerFacebookConnect
     *
     * .
     *
     */
    public function testAppControllerFacebookConnect()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for appControllerFacebookConnectRedirect
     *
     * .
     *
     */
    public function testAppControllerFacebookConnectRedirect()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for appControllerFacebookLogin
     *
     * .
     *
     */
    public function testAppControllerFacebookLogin()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for appControllerFacebookLoginRedirect
     *
     * .
     *
     */
    public function testAppControllerFacebookLoginRedirect()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for appControllerInstagramConnect
     *
     * .
     *
     */
    public function testAppControllerInstagramConnect()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for appControllerInstagramConnectRedirect
     *
     * .
     *
     */
    public function testAppControllerInstagramConnectRedirect()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for appControllerInstagramLogin
     *
     * .
     *
     */
    public function testAppControllerInstagramLogin()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for appControllerInstagramLoginRedirect
     *
     * .
     *
     */
    public function testAppControllerInstagramLoginRedirect()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for appControllerLanding
     *
     * .
     *
     */
    public function testAppControllerLanding()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for appControllerLoginWithClientCredentials
     *
     * .
     *
     */
    public function testAppControllerLoginWithClientCredentials()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for appControllerLogout
     *
     * .
     *
     */
    public function testAppControllerLogout()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for appControllerPointBadge
     *
     * .
     *
     */
    public function testAppControllerPointBadge()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for appControllerSse
     *
     * .
     *
     */
    public function testAppControllerSse()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for appControllerTwitterConnect
     *
     * .
     *
     */
    public function testAppControllerTwitterConnect()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for appControllerTwitterConnectRedirect
     *
     * .
     *
     */
    public function testAppControllerTwitterConnectRedirect()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for appControllerTwitterLogin
     *
     * .
     *
     */
    public function testAppControllerTwitterLogin()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for appControllerTwitterLoginRedirect
     *
     * .
     *
     */
    public function testAppControllerTwitterLoginRedirect()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for emailTemplateControllerCreate
     *
     * .
     *
     */
    public function testEmailTemplateControllerCreate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for emailTemplateControllerFindOne
     *
     * .
     *
     */
    public function testEmailTemplateControllerFindOne()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for emailTemplateControllerIndex
     *
     * .
     *
     */
    public function testEmailTemplateControllerIndex()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for emailTemplateControllerLoginForm
     *
     * .
     *
     */
    public function testEmailTemplateControllerLoginForm()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for emailTemplateControllerProcessLogin
     *
     * .
     *
     */
    public function testEmailTemplateControllerProcessLogin()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for platformConnectionControllerCreate
     *
     * .
     *
     */
    public function testPlatformConnectionControllerCreate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for platformConnectionControllerFindAll
     *
     * .
     *
     */
    public function testPlatformConnectionControllerFindAll()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for platformConnectionControllerFindOne
     *
     * .
     *
     */
    public function testPlatformConnectionControllerFindOne()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for platformConnectionControllerRemove
     *
     * .
     *
     */
    public function testPlatformConnectionControllerRemove()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for platformConnectionControllerUpdate
     *
     * .
     *
     */
    public function testPlatformConnectionControllerUpdate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for pointEventControllerFindAll
     *
     * .
     *
     */
    public function testPointEventControllerFindAll()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for pointEventControllerFindOne
     *
     * .
     *
     */
    public function testPointEventControllerFindOne()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for pointEventControllerRemove
     *
     * .
     *
     */
    public function testPointEventControllerRemove()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for pointEventControllerUpdate
     *
     * .
     *
     */
    public function testPointEventControllerUpdate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for userControllerCreate
     *
     * .
     *
     */
    public function testUserControllerCreate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for userControllerFindOne
     *
     * .
     *
     */
    public function testUserControllerFindOne()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for userControllerFindOneByEmail
     *
     * .
     *
     */
    public function testUserControllerFindOneByEmail()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for userControllerRemove
     *
     * .
     *
     */
    public function testUserControllerRemove()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for userControllerUpdate
     *
     * .
     *
     */
    public function testUserControllerUpdate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
